package prod;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ae' at '19/06/18 21:39' with Gradle 2.10
 *
 * @author ae, @date 19/06/18 21:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
