package acceptance;

import static org.junit.Assert.assertTrue;
import org.junit.Test;
import prod.Library;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ae' at '19/06/18 21:39' with Gradle 2.10
 *
 * @author ae, @date 19/06/18 21:39
 */
public class LibraryTest {

	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}

	@Test
	public void integrationTest() {
		assertTrue("A".contentEquals("B"));
	}
}
